# Change these first
owner: galpt # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
- name: 0ms.dev Home Page
  url: https://0ms.dev

assignees:
- galpt

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.0ms.dev
  # baseUrl: /your-repo-name
  logoUrl: https://s1.0ms.dev/assets/internal/check.png
  theme: dark
  name: 0ms.dev | Status
  introTitle: "Uptime status for 0ms.dev services"
  introMessage: This page aims to provide uptime information for users of our services, especially [DNS](https://0ms.dev/) and [Mirrors](https://0ms.dev/mirrors/).
  navbar:
  - title: Uptime
    href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
