# Change these first
owner: galpt # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
- name: vv Landing Page
  url: https://vv.services
- name: vv DNS
  url: https://vv.services/dns/
- name: vv Bufferbloat Test
  url: https://vv.services/bufferbloat/

assignees:
- galpt

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.vv.services
  # baseUrl: /your-repo-name
  logoUrl: https://vv.services/assets/internal/check.png
  theme: dark
  name: vv.services | Status
  introTitle: "Uptime status for vv.services"
  introMessage: This page aims to provide uptime information for users of our services, especially [DNS](https://vv.services/dns/).
  navbar:
  - title: Uptime
    href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
